### ISSUE TITLE
Does the Mass Enrolments plugin read the language pack?

### ISSUE THREAD

**Issue by joshuarbholden** [patrickpollet/moodle_local_mass_enroll#3]
My site has the language pack set to American English and "enroll" is being spelled with two l's everywhere except in the Mass Enrolments plugin.  Is that because the plugin isn't programmed to read the language pack, or is there something we need to configure?  Thanks!

----Josh

**Comment by patrickpollet** [comment]
Hi Josh

The plugin do have its own language file located in local/mass_enroll/lang/en/local_mass_enroll.php , together with some other languages. 

Since I am not a native english speaker, I surely have done some spelling mistakes when writing it. Please feel free to correct them ; it is as easy as changing the text between single quotes in the right parts of the php instructions such as 

$string['mass_enroll:enrol'] = 'Enrol users to a course by CSV file';

$string['mass_enroll:enrol'] = 'Enroll users to a course by CSV file'; 

Note that with recent versions of Moodle you must clear the language cache to see your changes onscreen see http://docs.moodle.org/22/en/Cache
<i>
Language packs - when language's are customized, part of the process is to refresh the language caches. The site administrator will see several language cache options in Site administration > Language > Language settings. 
</i>

I you do so, please send the revised version here, either as a pull request or an attachement to an issue and I shall be more than please to include it in the general release.

Thanks for your contribution.

**Comment by joshuarbholden** [comment]
Hi, Patrick!  Thanks very much for writing.

I see how this works now.  Not spelling mistakes at all; just the difference between British/Australian English and American English.  I guess the solution is to create a lang/en_us directory?  I've made what seem like the appropriate changes for that version of the file and I'll attach the new file here if I can figure out how.  (I confess I've never used GitHub before!)

Thanks again for your help,

Josh

**Comment by joshuarbholden** [comment]
I couldn't figure out how to attach a text file here so I created a pull request.  Hope I did it right!

Thanks,

----Josh
