### ISSUE TITLE
error in block recent activity

### ISSUE THREAD

**Issue by PatLemaire** [patrickpollet/moodle_local_mass_enroll#5]
Hi, Patrick!

Everytime my users use this script there is an error from database with the "Recent Activity" Block.
Here is an exemple of Debug info :

> Debug info: ERROR: invalid input syntax for integer: "Inscriptions massives"
> SELECT u.id, u.firstname, u.lastname, MAX(l.time)
> FROM mdl_user u, mdl_role_assignments ra, mdl_log l
> WHERE l.time > $1
> AND l.course = $2
> AND l.module = 'course'
> AND l.action = 'enrol'
> AND CAST(l.info AS INT) = u.id
> AND u.id = ra.userid
> AND ra.contextid IN (182,3,1)
> GROUP BY u.id, u.firstname, u.lastname
> ORDER BY MAX(l.time) ASC
> [array (
> 0 => 1414853300,
> 1 => '20',
> )]
> Error code: dmlreadexception
> Stack trace:
> 
>    line 425 of /lib/dml/moodle_database.php: dml_read_exception thrown
>    line 252 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
>    line 757 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
>    line 423 of /lib/deprecatedlib.php: call to pgsql_native_moodle_database->get_records_sql()
>    line 109 of /blocks/recent_activity/block_recent_activity.php: call to get_recent_enrolments()
>    line 72 of /blocks/recent_activity/block_recent_activity.php: call to block_recent_activity->get_recent_enrolments()
>    line 292 of /blocks/moodleblock.class.php: call to block_recent_activity->get_content()
>    line 238 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
>    line 951 of /lib/blocklib.php: call to block_base->get_content_for_output()
>    line 1003 of /lib/blocklib.php: call to block_manager->create_block_contents()
>    line 353 of /lib/blocklib.php: call to block_manager->ensure_content_created()
>    line 7 of /theme/univ_rouen/layout/general.php: call to block_manager->region_has_content()
>    line 864 of /lib/outputrenderers.php: call to include()
>    line 794 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
>    line 251 of /course/view.php: call to core_renderer->header()

My environnement : Moodle 2.5.7, PHP 5.3.3, PostGreSQL 8.4.
The only remedy is to reset the course history. I believe the problem could come from the PostGreSQL's syntax.

Thanks for your help.
Patrick

**Comment by patrickpollet** [comment]
Hi Patrick

 This is due to the fact that method block_recent_activity->get_recent_enrolments() in 2.5 still calls the deprecated function get_recent_enrolments() (in lib/deprecatedlib.php) whereas starting at 2.6 it use its own code ; see https://tracker.moodle.org/browse/MDL-40649

You may 'easily' fix it in 2.5 by commenting out the two calls to add_to_log() in scripts  local/mass_enroll/mass_enroll.php (line 90) and local/mass_enroll/mass_unenroll.php (line 92)

Since add_to_log() has been also deprecated in 2.7, I shall have to provide a better fix, if time permit ( \* et comme tu le sais, mon cher Patrick, j'ai comme notre ami Joseph, une forte attirance vers mon jardin ces derniers mois ;-) \* )

Cheers.

**Comment by patrickpollet** [comment]
Fixed for  Moodle < 2.7 see https://github.com/patrickpollet/moodle_local_mass_enroll/commit/b54118b63cae5ff3806474832a1b49dee0c379f4

**Comment by PatLemaire** [comment]
Thank you ! Everything is working perfectly now.
(\* profite bien de ton jardin, c'est largement mérité *)
